<?php
    $film = $this->data

?>
<!doctype html>
<html lang="en">
  <head>
  <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
    crossorigin="anonymous">
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
  </head>
  <body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">CINEMA-XII</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Now Playing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Theaters</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Info-XII
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Cinema News</a></li>
            <li><a class="dropdown-item" href="#">News Opening</a></li>
            <!-- <li><hr class="dropdown-divider"></li> -->
            <!-- <li><a class="dropdown-item" href="#">Something else here</a></li> -->
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search  movie here ..." aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <center><h1>NOW PLAYING</h1>
                <br></br>
                <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-3 row-cols-xl-5 justify-content-center" id="film">
                   
                </div>
            </div>
            <div class="container px-4 px-lg-5 mt-5">
                <center><h1>PILIH KURSI</h1></center>
                <br>
                <div class="row gx-4 gx-lg-5 row-cols-5 row-cols-md-3 row-cols-xl-5 justify-content-center">
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" id="A1">A1</a></div>
                        </div>
                        <script src="script.js"></script>
                    </div>
                    
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" id="A2"  >A2</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >A3</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >A4</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >A5</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >B1</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >B2</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >B3</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >B4</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >B5</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >C1</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >C2</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >C3</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >C4</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >C5</a></div>
                        </div>
                    </div>
                </div>  
                <br>
                <br><br><br>
                <div class="col mb-5">
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-success mt-auto" href="http://localhost:8081/MyCRUDSHARE/module/Application/view/application/index/invoice.phtml#!">Submit</a></div>
                            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                Launch demo modal
                            </button>

                        </div>
                    </div>  
            </div>
        </section>
        <!-- Button trigger modal -->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
    <script>
    $(document).ready(function(){ 
        var tombol = [];
        // Mendapatkan semua elemen tombol dengan kelas "btn-outline-dark"
        var buttons = document.querySelectorAll('.btn-outline-dark');

        // Loop melalui setiap tombol dan tambahkan event listener
        buttons.forEach(function(button) {
            // Simpan warna latar belakang asli
            var originalBackgroundColor = button.style.backgroundColor;

            button.addEventListener('click', function() {
                // Cek apakah tombol sudah berubah warna atau belum
                if (button.style.backgroundColor === 'black') {
                    // Jika sudah, kembalikan ke warna asli
                    button.style.backgroundColor = originalBackgroundColor;
                    button.style.color = ''; // Mengubah warna teks menjadi putih
                    var index = tombol.indexOf(button.id);
                    if (index !== -1) {
                        tombol.splice(index, 1);
                    }

                } else {
                    // Jika belum, ubah ke warna hitam
                    button.style.backgroundColor = 'black';
                    button.style.color = 'white'; // Mengubah warna teks menjadi putih
                    tombol.push(button.id);
                }
                console.log("Tombol aktif:", tombol);
            });
        });

        function decodeBase64Image(base64Str) {
            let bytes = atob(base64Str);
            let uint8Array = new Uint8Array(bytes.length);

            for(let i = 0; i < bytes.length; i++) {
                uint8Array[i] = bytes.charCodeAt(i);
            }

            let blob = new Blob([uint8Array], {type: "image/jpeg"}); 
            return URL.createObjectURL(blob);
        }
        $.ajax({
			url: '<?php echo $this->basePath()?>/application/film/read', // ini API nya
			type: "GET",
			dataType: 'json',
			success: function(response) {
				var data = response;
                
                // Membuat variabel untuk menyimpan HTML
                var html = '';

                // Iterasi melalui setiap objek film dalam array data
                $.each(data, function(index, film) {
                    let imageBase64 = film.film_image;
                    let imageUrl = decodeBase64Image(imageBase64);

                    // Membuat tag <div> untuk setiap film dengan kelas "col mb-5"
                    html += '<div class="col mb-5">';
                    html += '<div class="card h-100">';
                    html += '<img class="card-img-top" src="' + imageUrl + '" alt="..." />'; // Ganti dengan URL gambar sesuai respons API
                    html += '<div class="card-body p-4">';
                    html += '<div class="text-center">';
                    html += '<h5 class="fw-bolder">' + film.nama_film + '</h5>'; // Ganti dengan judul film sesuai respons API
                    html += 'Rp. ' + film.harga_tiket + '<br>'; // Ganti dengan harga film sesuai respons API
                    html += film.jam_tayang + '<br>'; // Ganti dengan waktu tayang sesuai respons API
                    html += '</div>';
                    html += '</div>';
                    html += '</div>';
                    html += '</div>';
                });

                // Memasukkan HTML yang telah dibuat ke dalam elemen dengan kelas "row"
                $('#film').html(html);
			}
            
		});
    })

</script>

  </body>
</html>



<!-- <div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div> -->
